### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by felixhahnweilheim** [WebCrew/humhub_flathub_updated#10]
## To do

- [ ] mobile view: space and profile header
- [ ] mobile view: styling of top navigation dropdown menu
- [ ] mobile view: overlapping stream entries
- [ ] forms: positioning of checkboxes
- [ ] My spaces dropdown: fix link to "Spaces" page, not old directory
- [ ]  #7 
- [x] #6 
- [x] Logo and icon (border-radius problem), see https://community.humhub.com/comment/perma?id=45313

Please feel free to make a PR to any of these points.

**Comment by WebCrew** [comment]
- Dark mode: text contrast is fixed now
- Logo is no longer round in a circle, so it is also fixed

That being said, we found that for every bug that was fixed, **more new ones were found to no small extent**. @felixhahnweilheim and me @WebCrew decided to throw in the towel here, **it doesn't make any sense anymore and it's not fun either**.

If you want a **dark theme**, try Felix's **Darkmode Module**. Found in the **HumHub Marketplace**.
